import { invoke } from "@tauri-apps/api/core";
import { emitTaskChanged } from "@/lib/taskEvents";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { useSectionStore } from "@/stores/sectionStore";
import type { BoardSection } from "@/types/section";

vi.mock("@/lib/taskEvents", () => ({
  emitTaskChanged: vi.fn(),
  onTaskChanged: vi.fn().mockResolvedValue(() => {}),
  TASK_CHANGED: "task-changed",
}));

const mockInvoke = vi.mocked(invoke);
const mockAnnounce = vi.mocked(emitTaskChanged);

function section(overrides: Partial<BoardSection> = {}): BoardSection {
  return {
    id: "section-1",
    boardKind: "priority",
    title: "JOB SEARCH",
    position: 0,
    ...overrides,
  };
}

/** Resets the store between tests — zustand state is module-level. */
function reset() {
  useSectionStore.setState({ sections: [], loading: false, error: null });
}

/** A promise plus the handles to settle it, for observing intermediate state. */
function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

beforeEach(() => {
  mockInvoke.mockReset();
  mockAnnounce.mockReset();
  reset();
});

describe("loading", () => {
  it("populates sections from the backend", async () => {
    mockInvoke.mockResolvedValue([section()]);

    await useSectionStore.getState().load("priority");

    expect(mockInvoke).toHaveBeenCalledWith("section_list", {
      boardKind: "priority",
    });
    expect(useSectionStore.getState().sections).toHaveLength(1);
    expect(useSectionStore.getState().loading).toBe(false);
  });

  it("records an error instead of throwing", async () => {
    mockInvoke.mockRejectedValue({ kind: "storage", message: "disk full" });

    await useSectionStore.getState().load("priority");

    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
    expect(useSectionStore.getState().loading).toBe(false);
  });

  it("orders sections by position", async () => {
    mockInvoke.mockResolvedValue([
      section({ id: "b", position: 2 }),
      section({ id: "a", position: 1 }),
    ]);

    await useSectionStore.getState().load("priority");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["a", "b"]);
  });
});

describe("sections", () => {
  it("creates a section and stores the server's version", async () => {
    // No optimistic insert: the id and the position are generated by Rust.
    mockInvoke.mockResolvedValue(section({ id: "new", title: "HEALTH" }));

    await useSectionStore.getState().addSection("priority", "HEALTH");

    expect(mockInvoke).toHaveBeenCalledWith("section_create", {
      boardKind: "priority",
      title: "HEALTH",
    });
    expect(useSectionStore.getState().sections[0]?.id).toBe("new");
  });

  it("keeps a created section in position order", async () => {
    useSectionStore.setState({ sections: [section({ id: "a", position: 5 })] });
    mockInvoke.mockResolvedValue(section({ id: "b", position: 1 }));

    await useSectionStore.getState().addSection("priority", "Earlier");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["b", "a"]);
  });

  it("renames through the rename command", async () => {
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockResolvedValue(section({ title: "Renamed" }));

    await useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(mockInvoke).toHaveBeenCalledWith("section_rename", {
      id: "section-1",
      title: "Renamed",
    });
    expect(useSectionStore.getState().sections[0]?.title).toBe("Renamed");
  });

  it("shows a rename before the backend responds", () => {
    useSectionStore.setState({ sections: [section()] });
    const pending = deferred<BoardSection>();
    mockInvoke.mockReturnValue(pending.promise);

    // Deliberately not awaited: the point is the state *during* the request.
    void useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(useSectionStore.getState().sections[0]?.title).toBe("Renamed");

    pending.resolve(section({ title: "Renamed" }));
  });

  it("rolls a failed rename back to the exact prior value", async () => {
    useSectionStore.setState({ sections: [section({ title: "original" })] });
    mockInvoke.mockRejectedValue({ kind: "storage", message: "constraint" });

    await useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(useSectionStore.getState().sections[0]?.title).toBe("original");
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });

  it("removes only the section it was given", async () => {
    useSectionStore.setState({
      sections: [section({ id: "a" }), section({ id: "b", position: 1 })],
    });
    mockInvoke.mockResolvedValue(undefined);

    await useSectionStore.getState().removeSection("a");

    expect(mockInvoke).toHaveBeenCalledWith("section_delete", { id: "a" });
    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["b"]);
  });

  it("restores a section when its delete fails", async () => {
    useSectionStore.setState({ sections: [section({ id: "a" })] });
    mockInvoke.mockRejectedValue({ kind: "storage", message: "locked" });

    await useSectionStore.getState().removeSection("a");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["a"]);
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });
});

describe("ordering after every operation", () => {
  it("re-sorts when the backend answers with a moved position", async () => {
    // The UI renders straight from this array, so a rename that comes back
    // with a new position must not leave the list in its old order.
    useSectionStore.setState({
      sections: [section({ id: "a", position: 0 }), section({ id: "b", position: 1 })],
    });
    mockInvoke.mockResolvedValue(section({ id: "a", position: 9 }));

    await useSectionStore.getState().renameSection("a", "Renamed");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["b", "a"]);
  });
});

describe("cross-window events", () => {
  it("announces a rename, because Rust moved the tasks under it", async () => {
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockResolvedValue(section({ title: "Renamed" }));

    await useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(mockAnnounce).toHaveBeenCalledTimes(1);
  });

  it("announces a delete, because Rust cleared the tasks under it", async () => {
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockResolvedValue(undefined);

    await useSectionStore.getState().removeSection("section-1");

    expect(mockAnnounce).toHaveBeenCalledTimes(1);
  });

  it("stays quiet when adding a section", async () => {
    // A new group touches no task, so no board's task list went stale.
    mockInvoke.mockResolvedValue(section({ id: "new" }));

    await useSectionStore.getState().addSection("priority", "HEALTH");

    expect(mockAnnounce).not.toHaveBeenCalled();
  });

  it("stays quiet when a rename or a delete is rejected", async () => {
    // Nothing changed, so no board needs to reload.
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockRejectedValue({ kind: "storage", message: "locked" });

    await useSectionStore.getState().renameSection("section-1", "Renamed");
    await useSectionStore.getState().removeSection("section-1");

    expect(mockAnnounce).not.toHaveBeenCalled();
  });
});
