import { invoke } from "@tauri-apps/api/core";
import { emitTaskChanged } from "@/lib/taskEvents";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { useSectionStore } from "@/stores/sectionStore";
import type { BoardSection, SectionItem } from "@/types/section";

vi.mock("@/lib/taskEvents", () => ({
  emitTaskChanged: vi.fn(),
  onTaskChanged: vi.fn().mockResolvedValue(() => {}),
  TASK_CHANGED: "task-changed",
}));

const mockInvoke = vi.mocked(invoke);
const mockAnnounce = vi.mocked(emitTaskChanged);

function item(overrides: Partial<SectionItem> = {}): SectionItem {
  return {
    id: "item-1",
    sectionId: "section-1",
    text: "chase the vendor",
    position: 0,
    ...overrides,
  };
}

function section(overrides: Partial<BoardSection> = {}): BoardSection {
  return {
    id: "section-1",
    boardKind: "priority",
    title: "Blocked on others",
    position: 0,
    items: [],
    ...overrides,
  };
}

/** Resets the store between tests — zustand state is module-level. */
function reset() {
  useSectionStore.setState({ sections: [], loading: false, error: null });
}

/** A promise plus the handles to settle it, for observing intermediate state. */
function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

beforeEach(() => {
  mockInvoke.mockReset();
  reset();
});

describe("loading", () => {
  it("populates sections from the backend", async () => {
    mockInvoke.mockResolvedValue([section()]);

    await useSectionStore.getState().load("priority");

    expect(mockInvoke).toHaveBeenCalledWith("section_list", {
      boardKind: "priority",
    });
    expect(useSectionStore.getState().sections).toHaveLength(1);
    expect(useSectionStore.getState().loading).toBe(false);
  });

  it("records an error instead of throwing", async () => {
    mockInvoke.mockRejectedValue({ kind: "storage", message: "disk full" });

    await useSectionStore.getState().load("priority");

    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
    expect(useSectionStore.getState().loading).toBe(false);
  });

  it("orders sections and their items by position", async () => {
    mockInvoke.mockResolvedValue([
      section({
        id: "b",
        position: 2,
        items: [
          item({ id: "b2", sectionId: "b", position: 5 }),
          item({ id: "b1", sectionId: "b", position: 1 }),
        ],
      }),
      section({ id: "a", position: 1 }),
    ]);

    await useSectionStore.getState().load("priority");

    const sections = useSectionStore.getState().sections;
    expect(sections.map((s) => s.id)).toEqual(["a", "b"]);
    expect(sections[1]?.items.map((i) => i.id)).toEqual(["b1", "b2"]);
  });
});

describe("sections", () => {
  it("creates a section and stores the server's version", async () => {
    // No optimistic insert: the id and the position are generated by Rust.
    mockInvoke.mockResolvedValue(section({ id: "new", title: "Waiting on" }));

    await useSectionStore.getState().addSection("priority", "Waiting on");

    expect(mockInvoke).toHaveBeenCalledWith("section_create", {
      boardKind: "priority",
      title: "Waiting on",
    });
    expect(useSectionStore.getState().sections[0]?.id).toBe("new");
  });

  it("keeps a created section in position order", async () => {
    useSectionStore.setState({ sections: [section({ id: "a", position: 5 })] });
    mockInvoke.mockResolvedValue(section({ id: "b", position: 1 }));

    await useSectionStore.getState().addSection("priority", "Earlier");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["b", "a"]);
  });

  it("renames through the rename command", async () => {
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockResolvedValue(section({ title: "Renamed" }));

    await useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(mockInvoke).toHaveBeenCalledWith("section_rename", {
      id: "section-1",
      title: "Renamed",
    });
    expect(useSectionStore.getState().sections[0]?.title).toBe("Renamed");
  });

  it("shows a rename before the backend responds", () => {
    useSectionStore.setState({ sections: [section()] });
    const pending = deferred<BoardSection>();
    mockInvoke.mockReturnValue(pending.promise);

    // Deliberately not awaited: the point is the state *during* the request.
    void useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(useSectionStore.getState().sections[0]?.title).toBe("Renamed");

    pending.resolve(section({ title: "Renamed" }));
  });

  it("rolls a failed rename back to the exact prior value", async () => {
    useSectionStore.setState({ sections: [section({ title: "original" })] });
    mockInvoke.mockRejectedValue({ kind: "storage", message: "constraint" });

    await useSectionStore.getState().renameSection("section-1", "Renamed");

    expect(useSectionStore.getState().sections[0]?.title).toBe("original");
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });

  it("removes a section and its items", async () => {
    useSectionStore.setState({
      sections: [
        section({ id: "a", items: [item({ id: "a1", sectionId: "a" })] }),
        section({ id: "b", position: 1 }),
      ],
    });
    mockInvoke.mockResolvedValue(undefined);

    await useSectionStore.getState().removeSection("a");

    expect(mockInvoke).toHaveBeenCalledWith("section_delete", { id: "a" });
    const sections = useSectionStore.getState().sections;
    expect(sections.map((s) => s.id)).toEqual(["b"]);
    expect(sections.flatMap((s) => s.items)).toHaveLength(0);
  });

  it("restores a section when its delete fails", async () => {
    useSectionStore.setState({
      sections: [section({ id: "a", items: [item({ id: "a1", sectionId: "a" })] })],
    });
    mockInvoke.mockRejectedValue({ kind: "storage", message: "locked" });

    await useSectionStore.getState().removeSection("a");

    const sections = useSectionStore.getState().sections;
    expect(sections.map((s) => s.id)).toEqual(["a"]);
    // Restored whole, items included — never half of the section.
    expect(sections[0]?.items.map((i) => i.id)).toEqual(["a1"]);
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });
});

describe("items", () => {
  beforeEach(() => {
    useSectionStore.setState({
      sections: [
        section({ id: "a", position: 0, items: [item({ id: "a1", sectionId: "a" })] }),
        section({ id: "b", position: 1, items: [item({ id: "b1", sectionId: "b" })] }),
      ],
    });
  });

  it("adds an item to the section it was addressed to", async () => {
    mockInvoke.mockResolvedValue(item({ id: "a2", sectionId: "a", position: 1 }));

    await useSectionStore.getState().addItem("a", "another one");

    expect(mockInvoke).toHaveBeenCalledWith("section_item_add", {
      sectionId: "a",
      text: "another one",
    });
    const sections = useSectionStore.getState().sections;
    expect(sections[0]?.items.map((i) => i.id)).toEqual(["a1", "a2"]);
    // The other section is left exactly as it was.
    expect(sections[1]?.items.map((i) => i.id)).toEqual(["b1"]);
  });

  it("keeps a new item in position order within its section", async () => {
    mockInvoke.mockResolvedValue(item({ id: "a0", sectionId: "a", position: -1 }));

    await useSectionStore.getState().addItem("a", "goes first");

    expect(useSectionStore.getState().sections[0]?.items.map((i) => i.id)).toEqual([
      "a0",
      "a1",
    ]);
  });

  it("leaves state untouched when adding an item fails", async () => {
    mockInvoke.mockRejectedValue({ kind: "storage", message: "disk full" });

    await useSectionStore.getState().addItem("a", "another one");

    const sections = useSectionStore.getState().sections;
    expect(sections.flatMap((s) => s.items).map((i) => i.id)).toEqual(["a1", "b1"]);
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });

  it("updates an item's text", async () => {
    mockInvoke.mockResolvedValue(item({ id: "a1", sectionId: "a", text: "edited" }));

    await useSectionStore.getState().updateItem("a1", "edited");

    expect(mockInvoke).toHaveBeenCalledWith("section_item_update", {
      id: "a1",
      text: "edited",
    });
    expect(useSectionStore.getState().sections[0]?.items[0]?.text).toBe("edited");
  });

  it("shows an edited item before the backend responds", () => {
    const pending = deferred<SectionItem>();
    mockInvoke.mockReturnValue(pending.promise);

    void useSectionStore.getState().updateItem("a1", "edited");

    expect(useSectionStore.getState().sections[0]?.items[0]?.text).toBe("edited");

    pending.resolve(item({ id: "a1", sectionId: "a", text: "edited" }));
  });

  it("rolls a failed edit back to the exact prior text", async () => {
    mockInvoke.mockRejectedValue({ kind: "storage", message: "constraint" });

    await useSectionStore.getState().updateItem("a1", "edited");

    expect(useSectionStore.getState().sections[0]?.items[0]?.text).toBe(
      "chase the vendor",
    );
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });

  it("removes an item from its section only", async () => {
    mockInvoke.mockResolvedValue(undefined);

    await useSectionStore.getState().removeItem("a1");

    expect(mockInvoke).toHaveBeenCalledWith("section_item_delete", { id: "a1" });
    const sections = useSectionStore.getState().sections;
    expect(sections[0]?.items).toHaveLength(0);
    expect(sections[1]?.items.map((i) => i.id)).toEqual(["b1"]);
  });

  it("restores an item when its delete fails", async () => {
    mockInvoke.mockRejectedValue({ kind: "storage", message: "locked" });

    await useSectionStore.getState().removeItem("a1");

    expect(useSectionStore.getState().sections[0]?.items.map((i) => i.id)).toEqual([
      "a1",
    ]);
    expect(useSectionStore.getState().error).toMatchObject({ kind: "storage" });
  });
});

describe("ordering after every operation", () => {
  it("re-sorts when the backend answers with a moved position", async () => {
    // The UI renders straight from this array, so a rename that comes back
    // with a new position must not leave the list in its old order.
    useSectionStore.setState({
      sections: [section({ id: "a", position: 0 }), section({ id: "b", position: 1 })],
    });
    mockInvoke.mockResolvedValue(section({ id: "a", position: 9 }));

    await useSectionStore.getState().renameSection("a", "Renamed");

    expect(useSectionStore.getState().sections.map((s) => s.id)).toEqual(["b", "a"]);
  });
});

describe("cross-window events", () => {
  it("never announces a section change", async () => {
    // Sections belong to one board and exactly one window shows that board,
    // so there is nobody to tell. Asserted so the asymmetry with taskStore
    // cannot be undone by accident.
    useSectionStore.setState({ sections: [section()] });
    mockInvoke.mockResolvedValue(section({ title: "Renamed" }));

    await useSectionStore.getState().renameSection("section-1", "Renamed");
    await useSectionStore.getState().addSection("priority", "Another");

    expect(mockAnnounce).not.toHaveBeenCalled();
  });
});
