/**
 * Task state for the boards.
 *
 * Every mutation is optimistic: local state changes immediately, the IPC call
 * follows, and a failure rolls back to the exact previous value. Board
 * interactions have to feel instant — a checkbox that waits on a database
 * round-trip feels broken even when it is fast.
 */

import { create } from "zustand";
import {
  createTask,
  deleteTask,
  listTasksByHorizon,
  listTasksForDate,
  listTasksForPeriod,
  rescheduleTask,
  toCommandError,
  updateTask,
} from "@/lib/ipc";
import type { CommandError, NewTask, Task, TaskHorizon, TaskPatch } from "@/types/task";

/** Which slice of tasks a board is showing. */
export type TaskFilter =
  | { kind: "horizon"; horizon: TaskHorizon }
  | { kind: "date"; date: string }
  | { kind: "period"; start: string; end: string };

/**
 * Sorts tasks for display: highest priority first, then oldest first.
 *
 * A standalone pure function rather than only a store method, because calling
 * a method inside a zustand selector returns a fresh array on every render and
 * sends React into an infinite loop. Components memoise this instead.
 */
export function sortTasks(tasks: Task[]): Task[] {
  return [...tasks].sort((a, b) => {
    // Unprioritised work sinks to the bottom rather than interleaving.
    const left = a.priority ?? -1;
    const right = b.priority ?? -1;
    if (left !== right) return right - left;
    return a.createdAt.localeCompare(b.createdAt);
  });
}

interface TaskState {
  /** Keyed by id so an optimistic update touches one entry, not an array. */
  tasks: Record<string, Task>;
  filter: TaskFilter | null;
  loading: boolean;
  error: CommandError | null;

  load: (filter: TaskFilter) => Promise<void>;
  clearError: () => void;

  add: (input: NewTask) => Promise<void>;
  complete: (id: string) => Promise<void>;
  uncomplete: (id: string) => Promise<void>;
  editTitle: (id: string, title: string) => Promise<void>;
  moveToDate: (id: string, date: string) => Promise<void>;
  promote: (id: string, horizon: TaskHorizon) => Promise<void>;
  remove: (id: string) => Promise<void>;

  orderedTasks: () => Task[];
}

function fetchFor(filter: TaskFilter): Promise<Task[]> {
  switch (filter.kind) {
    case "horizon":
      return listTasksByHorizon(filter.horizon);
    case "date":
      return listTasksForDate(filter.date);
    case "period":
      return listTasksForPeriod(filter.start, filter.end);
  }
}

export const useTaskStore = create<TaskState>((set, get) => {
  /**
   * Runs an optimistic mutation.
   *
   * Applies `optimistic` locally, awaits `commit`, then replaces the guess with
   * whatever the backend actually stored. On failure the previous value is
   * restored exactly — including its absence, so a failed delete reappears.
   */
  async function optimistic(
    id: string,
    guess: (task: Task) => Task,
    commit: (task: Task) => Promise<Task | null>,
  ) {
    const previous = get().tasks[id];
    if (!previous) return;

    set((state) => ({
      tasks: { ...state.tasks, [id]: guess(previous) },
      error: null,
    }));

    try {
      const stored = await commit(previous);

      set((state) => {
        const tasks = { ...state.tasks };
        if (stored) {
          tasks[id] = stored;
        } else {
          delete tasks[id];
        }
        return { tasks };
      });
    } catch (caught) {
      // Restore the exact prior value rather than re-fetching: the user is
      // looking at the row, and a flicker to a stale server state is worse
      // than simply undoing the change.
      set((state) => ({
        tasks: { ...state.tasks, [id]: previous },
        error: toCommandError(caught),
      }));
    }
  }

  async function patch(id: string, guess: (task: Task) => Task, body: TaskPatch) {
    await optimistic(id, guess, () => updateTask(id, body));
  }

  return {
    tasks: {},
    filter: null,
    loading: false,
    error: null,

    async load(filter) {
      set({ loading: true, filter });

      try {
        const loaded = await fetchFor(filter);
        set({
          tasks: Object.fromEntries(loaded.map((t) => [t.id, t])),
          error: null,
        });
      } catch (caught) {
        set({ error: toCommandError(caught) });
      } finally {
        set({ loading: false });
      }
    },

    clearError() {
      set({ error: null });
    },

    async add(input) {
      // No optimistic insert: the id is generated by Rust, and inventing a
      // temporary one only to swap it out invites duplicate rows on failure.
      try {
        const created = await createTask(input);
        set((state) => ({
          tasks: { ...state.tasks, [created.id]: created },
          error: null,
        }));
      } catch (caught) {
        set({ error: toCommandError(caught) });
      }
    },

    async complete(id) {
      const completedAt = new Date().toISOString();
      await patch(id, (t) => ({ ...t, status: "completed", completedAt }), {
        status: "completed",
        completedAt,
      });
    },

    async uncomplete(id) {
      // An explicit null clears the column. Omitting the key would mean
      // "leave alone", stranding a completion timestamp on an open task.
      await patch(id, (t) => ({ ...t, status: "planned", completedAt: null }), {
        status: "planned",
        completedAt: null,
      });
    },

    async editTitle(id, title) {
      await patch(id, (t) => ({ ...t, title }), { title });
    },

    async moveToDate(id, date) {
      // Through the reschedule command, never a plain update: only that path
      // counts the move as a deferral (spec §10.3).
      await optimistic(
        id,
        (t) => ({ ...t, scheduledDate: date }),
        () => rescheduleTask(id, date),
      );
    },

    async promote(id, horizon) {
      await patch(id, (t) => ({ ...t, horizon }), { horizon });
    },

    async remove(id) {
      // Not routed through `optimistic`, which swaps one task for another. A
      // delete has to remove the entry outright and put it back on failure.
      const previous = get().tasks[id];
      if (!previous) return;

      set((state) => {
        const tasks = { ...state.tasks };
        delete tasks[id];
        return { tasks, error: null };
      });

      try {
        await deleteTask(id);
      } catch (caught) {
        set((state) => ({
          tasks: { ...state.tasks, [id]: previous },
          error: toCommandError(caught),
        }));
      }
    },

    orderedTasks() {
      return sortTasks(Object.values(get().tasks));
    },
  };
});
